### PR TITLE
Move validator calls to IR layer

### PR DESCRIPTION
**Pull request by natestuder**
This improves emulation speed and hopefully fixes some odd behavior that was occurring with the validator in the translation layer.

### CODE REVIEW

**Comment by natestuder** [comment]
Commits are out of order in the review page, because they were re-arranged to be non-breaking without updating the commit date.

**Comment by amstrnad** [comment]
I think this fixes the intermittent failures (or at least one cause of them). I've re-run the branch a few times, and have yet to see any of the intermittent failures.

**Comment by sbrookes** [comment]
Just to confirm, we no longer need to run qemu with single-step. Is that correct?

**Comment by natestuder** [comment]
> Just to confirm, we no longer need to run qemu with single-step. Is that correct?

We shouldn't.  Probably should do some more testing to be sure though.

**Pull request merged**
